#!/bin/bash

OPTIONS="Logoff\nPower-off system\nReboot system\nSuspend system\nHibernate system"
LAUNCHER="/usr/bin/rofi -width 30 -dmenu -i -config /home/MYUSER/.config/i3/rofi/rofi-power.conf -p Power-Management"
LOCKER="/usr/local/bin/i3lockblur"

option=$(echo -e $OPTIONS | $LAUNCHER | awk '{print $1}' | tr -d '\r\n')

if [ ${#option} -gt 0 ]
then
    case $option in
      Logoff)
	/usr/bin/i3-msg exit
	;;
      Reboot)
        /bin/systemctl reboot
        ;;
      Power-off)
        /bin/systemctl poweroff
        ;;
      Suspend)
        "$LOCKER"; /bin/systemctl suspend
        ;;
      Hibernate)
        "$LOCKER"; /bin/systemctl hibernate
        ;;
      *)
        ;;
    esac
fi
